name: Patch

on: push  # to debug
# on:
#   push:
#     tags:
#       - '*.*.*'

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Build 5.x
        run: |
          if ($env:GITHUB_REF -eq "refs/heads/master") {
            BUILD_DIR = "master"
          } else {
            BUILD_DIR = ${env:GITHUB_REF} -replace ‘refs/tags/’, ‘’
          }
          Get-ChildItem Env:
          mkdir $BUILD_DIR
          cp -R Sophia/* $BUILD_DIR
          del -Force -Recurse "$BUILD_DIR/PowerShell 7.x"
          gci -Recurse

